Fix System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\WINDOWS\explorer.exe' with working directory 'AppContext.BaseDirectory'. 拒绝访问。 https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/180265099u/overview https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/3342720977u/overview https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/799855238u/overview https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/18523660u/overview https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/118999695u/overview
Try Fix
System.IO.IOException: The process cannot access the file 'C:\Users\***\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalState\Config.mpo' because it is being used by another process.
https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/2552968077u/overview

Try Fix
System.Runtime.InteropServices.COMException: 无法在设置线程模式后对其加以更改。 (0x80010106 (RPC_E_CHANGED_MODE))
https://appcenter.ms/orgs/BeyondDimension/apps/Steam/crashes/errors/1550045210u/overview